spring:
  datasource:
    url: jdbc:postgresql://heavenboards_postgres_instance:5432/user_service
    username: ${POSTGRES_DATABASE_USERNAME}
    password: ${POSTGRES_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog.xml
  docker:
    compose:
      enabled: false
      file: classpath:/docker-compose.yml
  web:
    resources:
      add-mappings: false
server:
  host: ${REMOTE_SERVER_HOST}
  port: 8093
  error:
    whitelabel:
      enabled: false
microservice:
  user-api:
    url: http://${server.host}:8093
  project-api:
    url: http://${server.host}:8094
  board-api:
    url: http://${server.host}:8095
  task-api:
    url: http://${server.host}:8096
jwt:
  secret: ${JWT_SECRET}
  expiration-time-seconds: 3600
