version: "3.9"
services:
  heavensboard-user-service-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "user_service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"
