version: "3.9"
services:
  heavenboards-user-service-postgres:
    image: postgres:15
    container_name: heavenboards_user_service_postgres
    environment:
      POSTGRES_DB: "user_service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"
